FROM pytorch/pytorch:2.1.2-cuda12.1-cudnn8-runtime

WORKDIR /app

# Memory fixes and HuggingFace cache directory
ENV PYTORCH_CUDA_ALLOC_CONF="expandable_segments:True"
ENV HF_HOME="/app/model_cache"

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY main.py .

EXPOSE 8000

# Start Uvicorn directly
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]