SELECT literacy_rate FROM education_stats e JOIN regions r ON e.region_id = r.region_id WHERE r.state_name = 'Maharashtra';
SELECT literacy_rate FROM education_stats e JOIN regions r ON e.region_id = r.region_id WHERE r.state_name = 'Uttar Pradesh';
SELECT t.tru_name, AVG(literacy_rate) FROM education_stats e JOIN tru t ON e.tru_id = t.tru_id GROUP BY t.tru_name;
SELECT r.state_name, literacy_rate FROM education_stats e JOIN regions r ON e.region_id = r.region_id ORDER BY literacy_rate DESC LIMIT 1;
SELECT r.state_name, literacy_rate FROM education_stats e JOIN regions r ON e.region_id = r.region_id ORDER BY literacy_rate ASC LIMIT 1;
SELECT gender, literacy_rate FROM education_stats e JOIN regions r ON e.region_id = r.region_id WHERE r.state_name = 'Kerala';
SELECT literacy_rate FROM education_stats e JOIN regions r ON e.region_id = r.region_id WHERE r.state_name = 'Tamil Nadu' AND gender = 'Female';
SELECT literacy_rate FROM education_stats e JOIN regions r ON e.region_id = r.region_id WHERE r.state_name = 'Bihar' AND gender = 'Male';
SELECT literacy_rate FROM education_stats e JOIN regions r ON e.region_id = r.region_id JOIN tru t ON e.tru_id = t.tru_id WHERE r.state_name = 'Rajasthan' AND t.tru_name = 'Rural';
SELECT r.state_name, AVG(literacy_rate) FROM education_stats e JOIN regions r ON e.region_id = r.region_id JOIN tru t ON e.tru_id = t.tru_id WHERE t.tru_name = 'Urban' GROUP BY r.state_name;
SELECT AVG(illiterate_population) FROM education_stats;
SELECT r.state_name, SUM(illiterate_population) FROM education_stats e JOIN regions r ON e.region_id = r.region_id GROUP BY r.state_name ORDER BY SUM(illiterate_population) DESC LIMIT 1;
SELECT a.age_group, AVG(literacy_rate) FROM education_stats e JOIN age_groups a ON e.age_group_id = a.age_group_id GROUP BY a.age_group;
SELECT AVG(literacy_rate) FROM education_stats e JOIN age_groups a ON e.age_group_id = a.age_group_id WHERE a.age_group = 'Working Age';
SELECT gender, AVG(literacy_rate) FROM education_stats GROUP BY gender;
SELECT worker_population_ratio FROM occupation_stats o JOIN regions r ON o.region_id = r.region_id WHERE r.state_name = 'Maharashtra';
SELECT worker_population_ratio FROM occupation_stats o JOIN regions r ON o.region_id = r.region_id WHERE r.state_name = 'Kerala';
SELECT r.state_name, worker_population_ratio FROM occupation_stats o JOIN regions r ON o.region_id = r.region_id ORDER BY worker_population_ratio DESC LIMIT 1;
SELECT r.state_name, worker_population_ratio FROM occupation_stats o JOIN regions r ON o.region_id = r.region_id ORDER BY worker_population_ratio ASC LIMIT 1;
SELECT SUM(main_workers) FROM occupation_stats o JOIN regions r ON o.region_id = r.region_id WHERE r.state_name = 'Uttar Pradesh';
SELECT SUM(marginal_workers) FROM occupation_stats o JOIN regions r ON o.region_id = r.region_id WHERE r.state_name = 'Bihar';
SELECT SUM(main_workers), SUM(marginal_workers) FROM occupation_stats;
SELECT AVG(non_workers) FROM occupation_stats;
SELECT t.tru_name, AVG(worker_population_ratio) FROM occupation_stats o JOIN tru t ON o.tru_id = t.tru_id GROUP BY t.tru_name;
SELECT gender, AVG(worker_population_ratio) FROM occupation_stats GROUP BY gender;
SELECT literacy_rate FROM education_stats e JOIN regions r ON e.region_id = r.region_id WHERE r.state_name = 'Karnataka';
SELECT literacy_rate FROM education_stats e JOIN regions r ON e.region_id = r.region_id WHERE r.state_name = 'Gujarat';
SELECT t.tru_name, gender, AVG(literacy_rate) FROM education_stats e JOIN tru t ON e.tru_id = t.tru_id GROUP BY t.tru_name, gender;
SELECT r.state_name, ABS(MAX(literacy_rate) - MIN(literacy_rate)) FROM education_stats e JOIN regions r ON e.region_id = r.region_id GROUP BY r.state_name ORDER BY ABS(MAX(literacy_rate) - MIN(literacy_rate)) DESC LIMIT 1;
SELECT r.state_name, AVG(literacy_rate) FROM education_stats e JOIN regions r ON e.region_id = r.region_id GROUP BY r.state_name;
SELECT literacy_rate FROM education_stats e JOIN regions r ON e.region_id = r.region_id JOIN tru t ON e.tru_id = t.tru_id WHERE r.state_name = 'Odisha' AND t.tru_name = 'Rural';
SELECT literacy_rate FROM education_stats e JOIN regions r ON e.region_id = r.region_id JOIN tru t ON e.tru_id = t.tru_id WHERE r.state_name = 'Delhi' AND t.tru_name = 'Urban';
SELECT literacy_rate FROM education_stats e JOIN regions r ON e.region_id = r.region_id WHERE r.state_name = 'Madhya Pradesh';
SELECT a.age_group, AVG(literacy_rate) FROM education_stats e JOIN age_groups a ON e.age_group_id = a.age_group_id GROUP BY a.age_group ORDER BY AVG(literacy_rate) DESC LIMIT 1;
SELECT a.age_group, AVG(literacy_rate) FROM education_stats e JOIN age_groups a ON e.age_group_id = a.age_group_id GROUP BY a.age_group ORDER BY AVG(literacy_rate) ASC LIMIT 1;
SELECT AVG(literacy_rate) FROM education_stats;
SELECT a.age_group, AVG(literacy_rate) FROM education_stats e JOIN age_groups a ON e.age_group_id = a.age_group_id GROUP BY a.age_group;
SELECT gender, AVG(literacy_rate) FROM education_stats GROUP BY gender;
SELECT worker_population_ratio FROM occupation_stats o JOIN regions r ON o.region_id = r.region_id WHERE r.state_name = 'Tamil Nadu';
SELECT worker_population_ratio FROM occupation_stats o JOIN regions r ON o.region_id = r.region_id WHERE r.state_name = 'Gujarat';
SELECT r.state_name, AVG(worker_population_ratio) FROM occupation_stats o JOIN regions r ON o.region_id = r.region_id GROUP BY r.state_name;
SELECT r.state_name, SUM(main_workers) FROM occupation_stats o JOIN regions r ON o.region_id = r.region_id GROUP BY r.state_name ORDER BY SUM(main_workers) DESC LIMIT 1;
SELECT r.state_name, SUM(marginal_workers) FROM occupation_stats o JOIN regions r ON o.region_id = r.region_id GROUP BY r.state_name ORDER BY SUM(marginal_workers) DESC LIMIT 1;
SELECT SUM(non_workers) FROM occupation_stats;
SELECT a.age_group, AVG(worker_population_ratio) FROM occupation_stats o JOIN age_groups a ON o.age_group_id = a.age_group_id GROUP BY a.age_group;
SELECT AVG(worker_population_ratio) FROM occupation_stats o JOIN age_groups a ON o.age_group_id = a.age_group_id WHERE a.age_group = 'Working Age';
SELECT AVG(worker_population_ratio) FROM occupation_stats o JOIN regions r ON o.region_id = r.region_id WHERE r.state_name = 'Maharashtra' AND gender = 'Female';
SELECT AVG(worker_population_ratio) FROM occupation_stats o JOIN regions r ON o.region_id = r.region_id WHERE r.state_name = 'Uttar Pradesh' AND gender = 'Male';
SELECT t.tru_name, AVG(worker_population_ratio) FROM occupation_stats o JOIN tru t ON o.tru_id = t.tru_id GROUP BY t.tru_name;
SELECT gender, AVG(worker_population_ratio) FROM occupation_stats GROUP BY gender;
SELECT literacy_rate FROM education_stats e JOIN regions r ON e.region_id = r.region_id WHERE r.state_name = 'Andhra Pradesh';
SELECT literacy_rate FROM education_stats e JOIN regions r ON e.region_id = r.region_id WHERE r.state_name = 'Telangana';
SELECT r.state_name, AVG(literacy_rate) FROM education_stats e JOIN regions r ON e.region_id = r.region_id GROUP BY r.state_name;
SELECT t.tru_name, AVG(literacy_rate) FROM education_stats e JOIN tru t ON e.tru_id = t.tru_id GROUP BY t.tru_name;
SELECT r.state_name, SUM(literate_population) FROM education_stats e JOIN regions r ON e.region_id = r.region_id GROUP BY r.state_name ORDER BY SUM(literate_population) DESC LIMIT 1;
SELECT r.state_name, SUM(literate_population) FROM education_stats e JOIN regions r ON e.region_id = r.region_id GROUP BY r.state_name ORDER BY SUM(literate_population) ASC LIMIT 1;
SELECT r.state_name, AVG(literacy_rate) FROM education_stats e JOIN regions r ON e.region_id = r.region_id WHERE gender = 'Male' GROUP BY r.state_name;
SELECT r.state_name, AVG(literacy_rate) FROM education_stats e JOIN regions r ON e.region_id = r.region_id WHERE gender = 'Female' GROUP BY r.state_name;
SELECT AVG(literacy_rate) FROM education_stats e JOIN regions r ON e.region_id = r.region_id JOIN age_groups a ON e.age_group_id = a.age_group_id WHERE r.state_name = 'Kerala' AND a.age_group = 'Working Age';
SELECT AVG(literacy_rate) FROM education_stats e JOIN age_groups a ON e.age_group_id = a.age_group_id WHERE a.age_group = 'Elderly';
SELECT worker_population_ratio FROM occupation_stats o JOIN regions r ON o.region_id = r.region_id WHERE r.state_name = 'Karnataka';
SELECT worker_population_ratio FROM occupation_stats o JOIN regions r ON o.region_id = r.region_id WHERE r.state_name = 'Andhra Pradesh';
SELECT r.state_name, AVG(worker_population_ratio) FROM occupation_stats o JOIN regions r ON o.region_id = r.region_id GROUP BY r.state_name;
SELECT r.state_name, worker_population_ratio FROM occupation_stats o JOIN regions r ON o.region_id = r.region_id ORDER BY worker_population_ratio ASC LIMIT 1;
SELECT SUM(main_workers + marginal_workers) FROM occupation_stats;
SELECT SUM(non_workers) FROM occupation_stats;
SELECT SUM(marginal_workers) FROM occupation_stats o JOIN regions r ON o.region_id = r.region_id WHERE r.state_name = 'Maharashtra';
SELECT SUM(main_workers) FROM occupation_stats o JOIN regions r ON o.region_id = r.region_id WHERE r.state_name = 'Tamil Nadu';
SELECT gender, AVG(worker_population_ratio) FROM occupation_stats GROUP BY gender;
SELECT t.tru_name, AVG(worker_population_ratio) FROM occupation_stats o JOIN tru t ON o.tru_id = t.tru_id WHERE gender = 'Female' GROUP BY t.tru_name;
SELECT t.tru_name, AVG(worker_population_ratio) FROM occupation_stats o JOIN tru t ON o.tru_id = t.tru_id WHERE gender = 'Male' GROUP BY t.tru_name;
SELECT AVG(worker_population_ratio) FROM occupation_stats o JOIN age_groups a ON o.age_group_id = a.age_group_id WHERE a.age_group = 'Young Adult';
SELECT AVG(worker_population_ratio) FROM occupation_stats o JOIN age_groups a ON o.age_group_id = a.age_group_id WHERE a.age_group = 'Elderly';
SELECT a.age_group, AVG(worker_population_ratio) FROM occupation_stats o JOIN age_groups a ON o.age_group_id = a.age_group_id GROUP BY a.age_group ORDER BY AVG(worker_population_ratio) DESC LIMIT 1;
SELECT a.age_group, AVG(worker_population_ratio) FROM occupation_stats o JOIN age_groups a ON o.age_group_id = a.age_group_id GROUP BY a.age_group ORDER BY AVG(worker_population_ratio) ASC LIMIT 1;
SELECT literacy_rate FROM education_stats e JOIN regions r ON e.region_id = r.region_id WHERE r.state_name = 'Punjab';
SELECT literacy_rate FROM education_stats e JOIN regions r ON e.region_id = r.region_id WHERE r.state_name = 'Haryana';
SELECT r.state_name, AVG(literacy_rate) FROM education_stats e JOIN regions r ON e.region_id = r.region_id GROUP BY r.state_name;
SELECT AVG(literacy_rate) FROM education_stats e JOIN regions r ON e.region_id = r.region_id JOIN tru t ON e.tru_id = t.tru_id WHERE r.state_name = 'Punjab' AND gender = 'Female' AND t.tru_name = 'Urban';
SELECT AVG(literacy_rate) FROM education_stats e JOIN regions r ON e.region_id = r.region_id JOIN tru t ON e.tru_id = t.tru_id WHERE r.state_name = 'Haryana' AND gender = 'Male' AND t.tru_name = 'Rural';
SELECT r.state_name, AVG(literacy_rate) FROM education_stats e JOIN regions r ON e.region_id = r.region_id GROUP BY r.state_name ORDER BY AVG(literacy_rate) DESC;
SELECT t.tru_name, gender, AVG(literacy_rate) FROM education_stats e JOIN tru t ON e.tru_id = t.tru_id GROUP BY t.tru_name, gender;
SELECT AVG(literacy_rate) FROM education_stats e JOIN regions r ON e.region_id = r.region_id JOIN age_groups a ON e.age_group_id = a.age_group_id WHERE r.state_name = 'Tamil Nadu' AND a.age_group = 'Young Adult';
SELECT AVG(literacy_rate) FROM education_stats e JOIN age_groups a ON e.age_group_id = a.age_group_id WHERE a.age_group = 'Middle Age';
SELECT AVG(literacy_rate) FROM education_stats;
SELECT worker_population_ratio FROM occupation_stats o JOIN regions r ON o.region_id = r.region_id WHERE r.state_name = 'Rajasthan';
SELECT worker_population_ratio FROM occupation_stats o JOIN regions r ON o.region_id = r.region_id WHERE r.state_name = 'West Bengal';
SELECT r.state_name, AVG(worker_population_ratio) FROM occupation_stats o JOIN regions r ON o.region_id = r.region_id GROUP BY r.state_name;
SELECT r.state_name, SUM(non_workers) FROM occupation_stats o JOIN regions r ON o.region_id = r.region_id GROUP BY r.state_name ORDER BY SUM(non_workers) DESC LIMIT 1;
SELECT r.state_name, SUM(non_workers) FROM occupation_stats o JOIN regions r ON o.region_id = r.region_id GROUP BY r.state_name ORDER BY SUM(non_workers) ASC LIMIT 1;
SELECT SUM(main_workers + marginal_workers) FROM occupation_stats WHERE gender = 'Female';
SELECT SUM(main_workers + marginal_workers) FROM occupation_stats WHERE gender = 'Male';
SELECT t.tru_name, AVG(worker_population_ratio) FROM occupation_stats o JOIN tru t ON o.tru_id = t.tru_id GROUP BY t.tru_name;
SELECT t.tru_name, AVG(worker_population_ratio) FROM occupation_stats o JOIN tru t ON o.tru_id = t.tru_id GROUP BY t.tru_name;
SELECT t.tru_name, gender, AVG(worker_population_ratio) FROM occupation_stats o JOIN tru t ON o.tru_id = t.tru_id GROUP BY t.tru_name, gender;
SELECT AVG(worker_population_ratio) FROM occupation_stats o JOIN age_groups a ON o.age_group_id = a.age_group_id WHERE a.age_group = 'Young Adult';
SELECT AVG(worker_population_ratio) FROM occupation_stats o JOIN age_groups a ON o.age_group_id = a.age_group_id WHERE a.age_group = 'Middle Age';
SELECT a.age_group, AVG(worker_population_ratio) FROM occupation_stats o JOIN age_groups a ON o.age_group_id = a.age_group_id GROUP BY a.age_group;
SELECT t.tru_name, SUM(main_workers) FROM occupation_stats o JOIN tru t ON o.tru_id = t.tru_id GROUP BY t.tru_name;
SELECT r.state_name, AVG(worker_population_ratio) FROM occupation_stats o JOIN regions r ON o.region_id = r.region_id GROUP BY r.state_name ORDER BY AVG(worker_population_ratio) DESC LIMIT 1;
SELECT a.age_group, AVG(literacy_rate) FROM education_stats e JOIN age_groups a ON e.age_group_id = a.age_group_id GROUP BY a.age_group;
SELECT r.state_name, AVG(literacy_rate) FROM education_stats e JOIN regions r ON e.region_id = r.region_id JOIN age_groups a ON e.age_group_id = a.age_group_id WHERE a.age_group = 'Young Adult' GROUP BY r.state_name ORDER BY AVG(literacy_rate) DESC LIMIT 1;
SELECT r.state_name, AVG(literacy_rate) FROM education_stats e JOIN regions r ON e.region_id = r.region_id JOIN age_groups a ON e.age_group_id = a.age_group_id WHERE a.age_group = 'Elderly' GROUP BY r.state_name ORDER BY AVG(literacy_rate) ASC LIMIT 1;
SELECT AVG(literacy_rate) FROM education_stats e JOIN regions r ON e.region_id = r.region_id WHERE gender = 'Female' AND r.region_name = 'South';
SELECT AVG(literacy_rate) FROM education_stats e JOIN regions r ON e.region_id = r.region_id WHERE gender = 'Male' AND r.region_name = 'North';
SELECT t.tru_name, gender, AVG(literacy_rate) FROM education_stats e JOIN tru t ON e.tru_id = t.tru_id GROUP BY t.tru_name, gender;
SELECT AVG(literacy_rate) FROM education_stats e JOIN age_groups a ON e.age_group_id = a.age_group_id WHERE gender = 'Female' AND a.age_group = 'Middle Age';
SELECT AVG(literacy_rate) FROM education_stats e JOIN age_groups a ON e.age_group_id = a.age_group_id WHERE gender = 'Male' AND a.age_group = 'Middle Age';
SELECT SUM(literate_population) FROM education_stats e JOIN tru t ON e.tru_id = t.tru_id WHERE t.tru_name = 'Urban';
SELECT SUM(literate_population) FROM education_stats e JOIN tru t ON e.tru_id = t.tru_id WHERE t.tru_name = 'Rural';
SELECT r.region_name, AVG(worker_population_ratio) FROM occupation_stats o JOIN regions r ON o.region_id = r.region_id GROUP BY r.region_name;
SELECT r.state_name, AVG(worker_population_ratio) FROM occupation_stats o JOIN regions r ON o.region_id = r.region_id WHERE gender = 'Female' GROUP BY r.state_name ORDER BY AVG(worker_population_ratio) DESC LIMIT 1;
SELECT r.state_name, AVG(worker_population_ratio) FROM occupation_stats o JOIN regions r ON o.region_id = r.region_id WHERE gender = 'Female' GROUP BY r.state_name ORDER BY AVG(worker_population_ratio) ASC LIMIT 1;
SELECT r.state_name, AVG(worker_population_ratio) FROM occupation_stats o JOIN regions r ON o.region_id = r.region_id WHERE gender = 'Male' GROUP BY r.state_name;
SELECT r.state_name, AVG(worker_population_ratio) FROM occupation_stats o JOIN regions r ON o.region_id = r.region_id WHERE gender = 'Female' GROUP BY r.state_name;
SELECT SUM(main_workers) * 100.0 / SUM(main_workers + marginal_workers) FROM occupation_stats;
SELECT SUM(marginal_workers) * 100.0 / SUM(main_workers + marginal_workers) FROM occupation_stats;
SELECT a.age_group, AVG(main_workers) FROM occupation_stats o JOIN age_groups a ON o.age_group_id = a.age_group_id GROUP BY a.age_group;
SELECT a.age_group, AVG(marginal_workers) FROM occupation_stats o JOIN age_groups a ON o.age_group_id = a.age_group_id GROUP BY a.age_group;
SELECT AVG(non_workers) FROM occupation_stats o JOIN age_groups a ON o.age_group_id = a.age_group_id WHERE a.age_group = 'Elderly';
SELECT SUM(main_workers + marginal_workers) FROM occupation_stats o JOIN tru t ON o.tru_id = t.tru_id WHERE gender = 'Female' AND t.tru_name = 'Urban';
SELECT SUM(main_workers + marginal_workers) FROM occupation_stats o JOIN tru t ON o.tru_id = t.tru_id WHERE gender = 'Male' AND t.tru_name = 'Rural';
SELECT AVG(worker_population_ratio) FROM occupation_stats o JOIN education_stats e ON o.region_id = e.region_id;
SELECT r.state_name, AVG(e.literacy_rate), AVG(o.worker_population_ratio) FROM education_stats e JOIN occupation_stats o ON e.region_id = o.region_id JOIN regions r ON e.region_id = r.region_id GROUP BY r.state_name;
SELECT r.region_name, AVG(worker_population_ratio) FROM occupation_stats o JOIN regions r ON o.region_id = r.region_id GROUP BY r.region_name;
SELECT AVG(e.literacy_rate) FROM education_stats e JOIN occupation_stats o ON e.region_id = o.region_id WHERE o.main_workers + o.marginal_workers > 0;
SELECT o.non_workers, AVG(e.literacy_rate) FROM education_stats e JOIN occupation_stats o ON e.region_id = o.region_id GROUP BY o.non_workers;
SELECT r.state_name, AVG(e.literacy_rate) FROM education_stats e JOIN occupation_stats o ON e.region_id = o.region_id JOIN regions r ON e.region_id = r.region_id WHERE o.main_workers + o.marginal_workers > 0 GROUP BY r.state_name ORDER BY AVG(e.literacy_rate) DESC LIMIT 1;
SELECT r.state_name, AVG(e.literacy_rate) FROM education_stats e JOIN occupation_stats o ON e.region_id = o.region_id JOIN regions r ON e.region_id = r.region_id WHERE o.non_workers > 0 GROUP BY r.state_name ORDER BY AVG(e.literacy_rate) ASC LIMIT 1;
SELECT AVG(e.literacy_rate) FROM education_stats e JOIN occupation_stats o ON e.region_id = o.region_id WHERE o.main_workers > o.marginal_workers;
SELECT AVG(worker_population_ratio) FROM occupation_stats o JOIN education_stats e ON o.region_id = e.region_id;
SELECT AVG(worker_population_ratio) FROM occupation_stats o JOIN education_stats e ON o.region_id = e.region_id WHERE e.literacy_rate IS NOT NULL;
SELECT AVG(worker_population_ratio) FROM occupation_stats o JOIN education_stats e ON o.region_id = e.region_id WHERE e.illiterate_population > 0;
SELECT gender, AVG(worker_population_ratio) FROM occupation_stats o JOIN education_stats e ON o.region_id = e.region_id GROUP BY gender;
SELECT AVG(worker_population_ratio) FROM occupation_stats o JOIN education_stats e ON o.region_id = e.region_id WHERE gender = 'Female';
SELECT AVG(e.literacy_rate) FROM education_stats e JOIN occupation_stats o ON e.region_id = o.region_id WHERE o.non_workers > 0;
SELECT e.literacy_rate, AVG(o.worker_population_ratio) FROM education_stats e JOIN occupation_stats o ON e.region_id = o.region_id GROUP BY e.literacy_rate;
SELECT a.age_group, AVG(o.worker_population_ratio) FROM occupation_stats o JOIN education_stats e ON o.region_id = e.region_id JOIN age_groups a ON e.age_group_id = a.age_group_id GROUP BY a.age_group;
SELECT AVG(o.non_workers) FROM occupation_stats o JOIN education_stats e ON o.region_id = e.region_id WHERE e.literacy_rate > 70;
SELECT AVG(e.literacy_rate) FROM education_stats e JOIN occupation_stats o ON e.region_id = o.region_id WHERE o.main_workers > 0;
SELECT AVG(e.literacy_rate) FROM education_stats e JOIN occupation_stats o ON e.region_id = o.region_id WHERE o.marginal_workers > 0;
SELECT r.state_name, AVG(o.worker_population_ratio) FROM occupation_stats o JOIN education_stats e ON o.region_id = e.region_id JOIN regions r ON o.region_id = r.region_id WHERE e.literacy_rate > 70 GROUP BY r.state_name;
SELECT r.state_name, AVG(o.worker_population_ratio) FROM occupation_stats o JOIN education_stats e ON o.region_id = e.region_id JOIN regions r ON o.region_id = r.region_id WHERE e.literacy_rate < 50 GROUP BY r.state_name;
SELECT r.state_name, AVG(e.literacy_rate), AVG(o.worker_population_ratio) FROM education_stats e JOIN occupation_stats o ON e.region_id = o.region_id JOIN regions r ON e.region_id = r.region_id GROUP BY r.state_name ORDER BY (AVG(e.literacy_rate)+AVG(o.worker_population_ratio)) DESC LIMIT 1;
SELECT r.state_name, AVG(e.literacy_rate), AVG(o.worker_population_ratio) FROM education_stats e JOIN occupation_stats o ON e.region_id = o.region_id JOIN regions r ON e.region_id = r.region_id GROUP BY r.state_name ORDER BY (AVG(e.literacy_rate)+AVG(o.worker_population_ratio)) ASC LIMIT 1;
SELECT SUM(o.main_workers + o.marginal_workers) * 100.0 / SUM(o.main_workers + o.marginal_workers + o.non_workers) FROM occupation_stats o JOIN education_stats e ON o.region_id = e.region_id WHERE e.literacy_rate IS NOT NULL;
SELECT SUM(o.main_workers + o.marginal_workers) * 100.0 / SUM(o.main_workers + o.marginal_workers + o.non_workers) FROM occupation_stats o JOIN education_stats e ON o.region_id = e.region_id WHERE e.illiterate_population > 0;
SELECT r.region_name, AVG(o.worker_population_ratio) FROM occupation_stats o JOIN education_stats e ON o.region_id = e.region_id JOIN regions r ON o.region_id = r.region_id GROUP BY r.region_name;
SELECT r.region_name, AVG(o.worker_population_ratio) FROM occupation_stats o JOIN education_stats e ON o.region_id = e.region_id JOIN regions r ON o.region_id = r.region_id WHERE e.literacy_rate > 70 GROUP BY r.region_name;
SELECT CORR(e.literacy_rate, o.worker_population_ratio) FROM education_stats e JOIN occupation_stats o ON e.region_id = o.region_id;